name: Update documentation

on:
  push:
    branches:
    - master

jobs:

  build:
    name: Trigger workflow in neic-sda
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.NEIC_SDA_ACCESS}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/norling/neic-sda/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "master"}'
